const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Flash,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Shape3D,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{"8Direções": 0},
	{Piscar: 0},
	{CentrarEm: 0},
	{Player_base: 0},
	{Mouse: 0},
	{Teclado: 0},
	{VidaInimigo: 0},
	{perseguir: 0},
	{CampoDeVisão: 0},
	{MoverPara: 0},
	{Inimigo: 0},
	{Projétil: 0},
	{Bala: 0},
	{Final_Do_Caminho: 0},
	{Fixar: 0},
	{Player_animation: 0},
	{Mosaico: 0},
	{Sólido: 0},
	{Parede_invisivel: 0},
	{"3Barris": 0},
	{BarrilFechado: 0},
	{BarrilAberto: 0},
	{Caveira: 0},
	{Muro: 0},
	{Pedrinha: 0},
	{PilarCaveira: 0},
	{Pilar: 0},
	{Vaso: 0},
	{VasoMadeira: 0},
	{Forma3D: 0},
	{Porta: 0},
	{PortaFim: 0},
	{PlanoDeFundoEmBlocos: 0},
	{FundoInicio: 0},
	{Título: 0},
	{Botão: 0},
	{VidaP1: 0},
	{VidaP2: 0},
	{VidaP3: 0},
	{FundoGameOver: 0},
	{PlayAgain: 0},
	{VoceMorreu: 0},
	{BotaoMenu: 0},
	{Interpolação: 0},
	{Fade: 0},
	{Âncora: 0},
	{Texto: 0},
	{Ponto: 0},
	{Sprite: 0},
	{Áudio: 0},
	{Sprite2: 0},
	{VoceVenceu: 0},
	{JogarNovamente: 0},
	{VoltarAoMenuFIM: 0},
	{Sprite3: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Vida: 0},
	{GameOver: 0},
	{CooldownTiro: 0},
	{Pontos: 0}
];

self.InstanceType = {
	Player_base: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Bala: class extends self.ISpriteInstance {},
	Final_Do_Caminho: class extends self.ISpriteInstance {},
	Player_animation: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Parede_invisivel: class extends self.ITilemapInstance {},
	_3Barris: class extends self.ISpriteInstance {},
	BarrilFechado: class extends self.ISpriteInstance {},
	BarrilAberto: class extends self.ISpriteInstance {},
	Caveira: class extends self.ISpriteInstance {},
	Muro: class extends self.ISpriteInstance {},
	Pedrinha: class extends self.ISpriteInstance {},
	PilarCaveira: class extends self.ISpriteInstance {},
	Pilar: class extends self.ISpriteInstance {},
	Vaso: class extends self.ISpriteInstance {},
	VasoMadeira: class extends self.ISpriteInstance {},
	Forma3D: class extends self.I3DShapeInstance {},
	Porta: class extends self.ISpriteInstance {},
	PortaFim: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	FundoInicio: class extends self.ISpriteInstance {},
	Título: class extends self.ISpriteInstance {},
	Botão: class extends self.ISpriteInstance {},
	VidaP1: class extends self.ISpriteInstance {},
	VidaP2: class extends self.ISpriteInstance {},
	VidaP3: class extends self.ISpriteInstance {},
	FundoGameOver: class extends self.ISpriteInstance {},
	PlayAgain: class extends self.ISpriteInstance {},
	VoceMorreu: class extends self.ISpriteInstance {},
	BotaoMenu: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Ponto: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	VoceVenceu: class extends self.ISpriteInstance {},
	JogarNovamente: class extends self.ISpriteInstance {},
	VoltarAoMenuFIM: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {}
}